.PHONY: build-backend
build-backend:
	go build -o ./bin/{{ .ProjectName }}

.PHONY: build-frontend
build-frontend:
	cd ui && \
	npm install && \
	npm run build

.PHONY: run
run: build
	./bin/{{ .ProjectName }}

.PHONY: build-all
build-all: build-backend build-frontend
	
